In [1]:
from google.colab import files
uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Titanic-Dataset.csv")

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
!pip install -q google-genai pandas matplotlib seaborn

In [8]:
import pandas as pd
import numpy as np

from google import genai
from google.genai import types

In [10]:
GEMINI_API_KEY = "AQ.Ab8RN6KnvXBismGM86FOtUHy8_Eiq1lO1QIqDJYUjwIOAx2mZw"

In [11]:
client = genai.Client(api_key=GEMINI_API_KEY)

In [12]:
from google.colab import files

uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset (1).csv

In [14]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
def ask_gemini(prompt):

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.2
        )
    )

    return response.text

In [18]:
prompt = """
Write Python pandas code to display the first five rows of dataframe df.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.head()
```

In [19]:
prompt = """
Write Python code to display dataframe information.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.info()
```

In [20]:
prompt = """
Write pandas code to find missing values in dataframe df.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.isnull().sum()
```

In [21]:
prompt = """
Write pandas code to calculate percentage of missing values.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.isnull().mean() * 100
```

In [22]:
prompt = """
Find duplicate rows in dataframe df.
Only return Python code.
"""

print(ask_gemini(prompt))

```python
df[df.duplicated()]
```

In [23]:
prompt = """
Remove duplicate rows from dataframe df.
Only return code.
"""

print(ask_gemini(prompt))

```python
df = df.drop_duplicates()
```

In [24]:
prompt = """
Fill numerical missing values using mean.
Only return pandas code.
"""

print(ask_gemini(prompt))

```python
df.fillna(df.mean(numeric_only=True), inplace=True)
```

In [25]:
prompt = """
Fill categorical missing values using mode.
Only return pandas code.
"""

print(ask_gemini(prompt))

```python
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc[0])
```

In [26]:
prompt = """
Rename all dataframe columns to lowercase.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.columns = df.columns.str.lower()
```

In [27]:
prompt = """
Remove extra spaces from string columns.
Only return pandas code.
"""
print(ask_gemini(prompt))

```python
df[df.select_dtypes(include=["object", "string"]).columns] = df.select_dtypes(
    include=["object", "string"]
).apply(lambda x: x.str.replace(r"\s+", " ", regex=True).str.strip())
```

In [28]:
prompt = """
Show dataframe shape.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.shape
```

In [29]:
prompt = """
Generate summary statistics of dataframe df.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.describe()
```

In [30]:
prompt = """
Detect outliers using IQR.
Only return code.
"""

print(ask_gemini(prompt))

```python
import numpy as np


def detect_outliers_iqr(data):
    data = np.asarray(data)
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    return data[(data < lower_bound) | (data > upper_bound)]
```

In [31]:
prompt = """
Remove outliers using IQR method.
Only return code.
"""

print(ask_gemini(prompt))

```python
import pandas as pd


def remove_outliers_iqr(df, columns):
    df_clean = df.copy()
    for col in columns:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_clean = df_clean[
            (df_clean[col] >= lower_bound) & (df_clean[col] <= upper_bound)
        ]
    return df_clean
```

In [32]:
prompt = """
Convert categorical variables into dummy variables.
Only return code.
"""

print(ask_gemini(prompt))

```python
import pandas as pd

# Assuming `df` is your DataFrame and `categorical_cols` is a list of categorical column names
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
```

In [33]:
prompt = """
Display column data types.
Only return code.
"""

print(ask_gemini(prompt))

```sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'your_table_name';
```

In [34]:
prompt = """
Count unique values in each column.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.nunique()
```

In [35]:
prompt = """
Drop rows with more than 50 percent missing values.
Only return code.
"""

print(ask_gemini(prompt))

```python
df = df.dropna(thresh=len(df.columns) / 2)
```

In [36]:
prompt = """
Save cleaned dataframe as cleaned_titanic.csv.
Only return code.
"""

print(ask_gemini(prompt))

```python
df.to_csv("cleaned_titanic.csv", index=False)
```

In [37]:
prompt = """
Generate a short summary describing the cleaning steps performed.
"""

print(ask_gemini(prompt))

It looks like you forgot to include the details!

Please provide the text, list, or description of the cleaning steps performed, and I will gladly generate a concise summary for you.

In [38]:
df.to_csv("cleaned_titanic.csv", index=False)